config/routes.rb
Rails.application.routes.draw do
  get 'books/new'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup', to:'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/booklist', to: 'books#index'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :books
  resources :comments
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
 <h2>名前について</h2>
<p>VCS-Miradorは、ソフトウェア開発で用いられる分散システム管理（Version Control System）を、電子資料のビュワーであるMiradorと組み合わせることで新しい人文学の共同研究の形を提案したいという思いを込めて名付けられました。</p>

<h2>できること</h2>
<p>VCS-Miradorでは各図書館が公開している電子資料を手元で一括して管理し、注釈を仲間どうしで加えることができます。また、Miradorのマルチウィンドウや注釈の機能が、人文学研究における様々な場面で役立つでしょう。</p>
<p>VCS-Miradorでは、グループを作成して、複数の研究者の間で注釈の共有をすることができます。この機能を用いて大量の資料画像を共同で扱うことできます。</p>

<h2>背景</h2>
<p>近年、International Image Interoperability Framework(IIIF)という電子資料に付与するメタデータの国際的なフォーマットが各国の図書館で採用されています。VCS-MiradorはこのIIIFに対応したビューワーであるMiradorをベースに作られています。IIIFに対応したビュワーによって、それまでは図書館ごとのビュワーで閲覧していた資料が１つのビュワーを通じて扱うことができるようになりました。</p>

<h2>利用方法</h2>
<p>まず、アカウントを作成します。アカウントを作成したら、右上のメニューボタンのDocumentsをクリックして、Adding a Documentを選択してください。</p>

<p>Adding a Documentのページでは、あなたが手元で管理したい資料をあなたのアカウントに追加することができます。nameでは、あなたが自分で資料の名前をつけることができます。次に、あなたがその図書館のビュワーで見ている時の資料のURLをコピーして、入力欄にペースとしてください。自動的にIIIFフォーマットのメタデータを取得して、Miradorによって閲覧することができるようになります。最後に、自分の追加した資料や注釈を見られたくないのであれば、is locked?のボタンにチェックをしてください。あとは、Add itをクリックするだけです。</p>

<p>新しい資料を追加すると、自動的にコメントページに移ります。コメントはannotation、idea、hypothesisの３種類から選ぶことができます。annotationは、書かれている内容の事実確認や、翻刻など、資料の考証のためにコメントつける時に使います。ideaはannotationでの蓄積から、これまでの解釈とは違った資料の見方ができる場合にその着想をメモするところです。最後のhypothesisはideaの中から新しい理論が立ち上がりそうな時に、annotationやideaを統合して、それについて考察を書くところです。ただし、これは研究の場面に合わせて異なった用い方をしても問題ありません。研究に最適なツールの使用をお勧めします。</p>

<h2>注意</h2>
<ul>
<li>
<li>現在は試験的に、Miradorの元となっているOpenSeadragonにて実装がなされています。段階的に、Miradorに移行していく予定です。</li>
<li>現在は個人のみで資料を管理するようになっていますが、段階的にグループで同じ資料と資料への注釈を管理できるようにしていく予定です。</li>
<li>現在、利用できる図書館はGallicaだけですが、DPLAやEuropeanaといった図書館に対応していく予定です。</li>
</ul>
</P>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p> 
<h3>以下のFAQを参考にしてください</h3>
<p>
Q. アカウントが作成できない。<br>
A. セキュリティの関係上、パスワードが短すぎる場合はアカウントを作成することができません。</p>
<p>Q. アカウントに入力した事項を変更したい。<br>
A. 現在、アプリケーションの運用は試験段階です。事項の変更は今後出来る様になります。</p>
<p>Q. 資料を追加してもコメントページに移動しない。<br>
A. もしもGallica以外の図書館の資料は現在扱うことができません。もしも、Gallicaの資料を入力してもコメントページに移動しない場合は、閲覧している資料の最初のページに戻って、そのURLを入力してください。</p>
<p>Q. コメントの使い方がよくわからない。<br>
A. 詳しくは、aboutの利用方法をご覧ください。</p>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to VCS-Mirador alpha</h1>

  <h2>
    your virtual library for humanities.
  </h2>

  <%= link_to "Sign up now!",signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>